# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 15:08
from __future__ import unicode_literals

import apostello.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_no_keyword_auto_reply', models.TextField(default='Thank you, %name%, your message has been received.', help_text='This message will be sent when a SMS matched a keyword, but that keyword has no reply set', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('default_no_keyword_not_live', models.TextField(default='Thank you, %name%, for your text. But "%keyword%" is not active..', help_text='Default message for when a keyword is not currently active.', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('keyword_no_match', models.TextField(default='Thank you, %name%, your message has not matched any of our keywords. Please correct your message and try again.', help_text='Reply to use when an SMS does not match any keywords', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('start_reply', models.TextField(default='Thanks for signing up!', help_text='Reply to use when someone matches "start"', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('name_update_reply', models.TextField(default='Thanks %s!', help_text='Reply to use when someone matches "name".', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('name_failure_reply', models.TextField(default="Something went wrong, sorry, please try again with the format 'name John Smith'.", help_text='Reply to use when someone matches "name"with bad formatting.', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
                ('auto_name_request', models.TextField(default="Hi there, I'm afraid we currently don't have your number inour address book. Could you please reply in the format\n'name John Smith'", help_text='Message to send when we first receive a message from someone not in the contacts list.', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit])),
            ],
            options={
                'verbose_name': 'Default Responses',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='apostello', max_length=255)),
                ('disable_email_login_form', models.BooleanField(default=False, help_text='Tick this to hide the login with email form. Note, you will need to have setup login with Google, or users will have no way into the site.')),
                ('sms_char_limit', models.PositiveSmallIntegerField(default=160, help_text='SMS length limit.')),
                ('disable_all_replies', models.BooleanField(default=False, help_text='Tick this box to disable all automated replies')),
                ('office_email', models.EmailField(blank=True, help_text='Email to send information emails to', max_length=254)),
                ('from_email', models.EmailField(blank=True, help_text='Email to send emails from', max_length=254)),
                ('slack_url', models.URLField(blank=True, help_text='Post all incoming messages to this slack hook. Leave blank to disable.')),
                ('sync_elvanto', models.BooleanField(default=False, help_text='Toggle automatic syncing of Elvanto groups. Sync will be done overnight')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
