# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("site_config", "0002_auto_20160221_1135")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="not_approved_msg",
            field=models.TextField(
                default="\n\nYour account has not yet been approved.\n\nAll new accounts require approval to help prevent abuse. Someone should approve your account soon.\n\nPlease get in touch if you believe you are seeing this in error.\n",
                help_text='This message will be shown on the "not approved" page.',
            ),
        )
    ]
