# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("site_config", "0003_siteconfiguration_not_approved_msg")]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_from",
            field=models.EmailField(
                blank=True,
                help_text="Email will be sent from this address. This will override values in settings.py",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_host",
            field=models.URLField(blank=True, help_text="Email host. This will override values in settings.py"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_password",
            field=models.CharField(
                blank=True, help_text="Email password. This will override values in settings.py", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_port",
            field=models.PositiveIntegerField(
                blank=True, help_text="Email host port. This will override values in settings.py", null=True
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="email_username",
            field=models.CharField(
                blank=True, help_text="Email user name. This will override values in settings.py", max_length=255
            ),
        ),
    ]
