# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 17:14
from __future__ import unicode_literals

import apostello.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0004_auto_20160422_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultresponses',
            name='auto_name_request',
            field=models.TextField(default="Hi there, I'm afraid we currently don't have your number in our address book. Could you please reply in the format\n'name John Smith'", help_text='Message to send when we first receive a message from someone not in the contacts list.', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit]),
        ),
        migrations.AlterField(
            model_name='defaultresponses',
            name='keyword_no_match',
            field=models.TextField(default='Thank you, %name%, your message has not matched any of our keywords. Please correct your message and try again.', help_text='Reply to use when an SMS does not match any keywords. ("%name%" will be replaced with the user\'s first name)', max_length=1000, validators=[apostello.validators.less_than_sms_char_limit]),
        ),
    ]
