# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 19:01
from __future__ import unicode_literals

import apostello.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0007_siteconfiguration_auto_add_new_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_number_prefix',
            field=models.CharField(blank=True, default='', help_text="This value will be used to prepopulate the new contact form use this if you don't want to have to type +xx every time.", max_length=5, validators=[apostello.validators.validate_starts_with_plus]),
        ),
    ]
