# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostello', '0002_siteconfiguration_disable_email_login_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElvantoGroup',
        ),
    ]
