# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostello', '0005_auto_20160221_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_tour',
            field=models.BooleanField(default=True, help_text='If true, the user will be shown popup tour on index page.'),
        ),
    ]
