# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 12:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostello', '0006_userprofile_show_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='first_name',
            field=models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator('^[\\s\\w@?£!1$"¥#è?¤é%ù&ì\\ò(Ç)*:Ø+;ÄäøÆ,<LÖlöæ\\-=ÑñÅß.>ÜüåÉ/§à¡¿\']+$', message='You can only use GSM characters.')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='last_name',
            field=models.CharField(db_index=True, max_length=40, validators=[django.core.validators.RegexValidator('^[\\s\\w@?£!1$"¥#è?¤é%ù&ì\\ò(Ç)*:Ø+;ÄäøÆ,<LÖlöæ\\-=ÑñÅß.>ÜüåÉ/§à¡¿\']+$', message='You can only use GSM characters.')], verbose_name='Last Name'),
        ),
    ]
