# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostello', '0009_userprofile_message_cost_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__email']},
        ),
    ]
