# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apostello", "0014_queuedsms")]

    operations = [migrations.AlterModelOptions(name="queuedsms", options={"ordering": ["time_to_send"]})]
