# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostello', '0016_auto_20170605_1537'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='smsinbound',
            index_together=set([('is_archived', 'matched_keyword')]),
        ),
    ]
