# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("apostello", "0017_auto_20170605_1605")]

    operations = [
        migrations.CreateModel(
            name="CloudMessageId",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=1000)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(name="cloudmessageid", unique_together=set([("url", "user")])),
    ]
