# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("apostello", "0018_auto_20170808_1045")]

    operations = [migrations.RemoveField(model_name="smsinbound", name="matched_link")]
